kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-transcode-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: vsan-thin-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
